### ISSUE TITLE
Able to add new field at root level in Pages collection type and get that field in generated payload

### ISSUE THREAD

**Issue by radixdt2144** [tezjs/tezjs#62]
### Description
When we add a new field in "Pages" collection type at root level from strapi backend, it's not generating in payload at frontend side.

Suppose 
1. I add new field "displayOrder" in "Pages" collection type at root level as shown in below image.

![pages](https://user-images.githubusercontent.com/92514919/188798563-b4f584f8-5f40-4eab-9a9b-90960ab0fa07.png)

2. When i generate the payload at frontend side, I didn't get that field in JSON file here as shown below.

![image](https://user-images.githubusercontent.com/92514919/188799279-a4b074dd-304e-4721-9193-415392a95fde.png)

### Describe the solution you'd like
Should able to add new fields at root level in collection type and get it in payload at frontend side.

Please provide provision for adding new fileds to collection type at root level and get it in JSON file in payload at frontend side.

**Comment by ajayojha** [comment]
Would like to know the purpose behind this. Which requirement is not fulfilled from the component level payload?

**Comment by radixdt2144** [comment]
### Scenario : I want one particular field on each page

**1. If I add new field at component level :**  
   - I have to create new component for that field and add it to the genericCollections in every page.
   - Also I have to give VueReferenceCode to particular component to get that data.

**2. If I add new field at root level then I can easily get that data at frontend side.**

Can you please guide us which approach is better ?

**Comment by ajayojha** [comment]
Here are my input on point 2:

>> 2. If I add new field at root level then I can easily get that data at frontend side.

Without a component, you cannot use the property on the page. 


I presume you need ease to access the property instead of adding multiple components in the `genericCollections`.  If this is the case then without a strong use case it should not consider as a feature request.

>> Can you please guide us which approach is better ?

I think currently you have full control on the component instead page component, so page-level property is not the better option (until we have a strong use-case). I would suggest if you wish to use the property on every page then try to add the component in the master pages and reference the master page on the respective page.

**Comment by ajayojha** [comment]
I am closing this ticket as no further update on this. Feel free to create a new ticket with appropriate use case :).
